version: '3.8'

services:
  app:
    container_name: Nebustest3
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/Nebustest3
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    ports:
      - "8000:8000"  # Проброс порта 8000 из контейнера на хост

  db:
    container_name: nebusbase3
    image: postgres:15
    restart: always
    ports:
      - "5443:5432"  # Маппинг порта PostgreSQL
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data  # Локальная папка для хранения данных

# Убедитесь, что volumes определены правильно:
volumes:
  postgres_data: {}  # Определение тома с пустым объектом
